import { maxLength, scopes, types } from './commit.config.ts'

// Validates a commit subject against the conventional format this repository uses.

export type Failure = {
  rule: string
  detail: string
}

const subjectOf = (message: string): string => {
  const [first] = message.split('\n')

  return (first ?? '').trim()
}

export const validate = (message: string): Failure[] => {
  const subject = subjectOf(message)
  const failures: Failure[] = []

  // A merge or revert subject is generated by git and is left alone.
  if (subject.startsWith('Merge ') || subject.startsWith('Revert ')) {
    return failures
  }

  const shape = /^([a-z]+)(?:\(([a-z-]+)\))?: (.+)$/.exec(subject)

  if (!shape) {
    failures.push({ rule: 'format', detail: 'a subject reads as type(scope): description' })

    return failures
  }

  const [, type, scope, description] = shape

  if (!type || !types.includes(type)) {
    failures.push({ rule: 'type', detail: `type must be one of ${types.join(', ')}` })
  }

  if (scope && !scopes.includes(scope)) {
    failures.push({ rule: 'scope', detail: `scope must be one of ${scopes.join(', ')}` })
  }

  if (description && /^[A-Z]/.test(description)) {
    failures.push({ rule: 'case', detail: 'a description starts with a lowercase letter' })
  }

  if (description && /[.!,;:]$/.test(description)) {
    failures.push({ rule: 'punctuation', detail: 'a description ends without punctuation' })
  }

  if (subject.length > maxLength) {
    failures.push({ rule: 'length', detail: `a subject fits within ${maxLength} characters` })
  }

  if (subject.includes('!:') || /\)!:/.test(subject)) {
    failures.push({ rule: 'breaking', detail: 'a breaking change belongs in a BREAKING CHANGE footer' })
  }

  return failures
}
